[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/EventBus"

[[constraint]]
  branch = "master"
  name = "github.com/myzhan/boomer"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/zeromq/goczmq"
  version = "4.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/zeromq/gomq"

[prune]
  go-tests = true
  unused-packages = true
